SELECT COUNT(*) AS PRICE_HISTORY
FROM PRICE_HISTORY;

SELECT COUNT(*) AS PRODUCT_IN_ORDERS
FROM PRODUCT_IN_ORDERS;

SELECT COUNT(*) AS PRODUCT_IN_SHOPS
FROM PRODUCT_IN_SHOPS;

SELECT COUNT(*) AS FEEDBACK
FROM FEEDBACK;

SELECT COUNT(*) AS PRODUCTS
FROM PRODUCTS;

SELECT COUNT(*) AS COMPLAINTS_ON_SHOPS
FROM COMPLAINTS_ON_SHOPS;

SELECT COUNT(*) AS COMPLAINTS_ON_ORDERS
FROM COMPLAINTS_ON_ORDERS;

SELECT COUNT(*) AS COMPLAINTS
FROM COMPLAINTS;

SELECT COUNT(*) AS EMPLOYEES
FROM EMPLOYEES;

SELECT COUNT(*) AS ORDERS
FROM ORDERS;

SELECT COUNT(*) AS USERS
FROM USERS;

SELECT COUNT(*) AS SHOPS
FROM SHOPS;
