DELETE FROM PRODUCTS;
INSERT INTO PRODUCTS VALUES ('1', 'iPhone X', 'Apple', 'Electronics');
INSERT INTO PRODUCTS VALUES ('2', 'iPhone XS', 'Apple', 'Electronics');
INSERT INTO PRODUCTS VALUES ('3', 'iPhone 11', 'Apple', 'Electronics');
INSERT INTO PRODUCTS VALUES ('4', 'iPhone 12', 'Apple', 'Electronics');
INSERT INTO PRODUCTS VALUES ('5', 'Samsung S22', 'Samsung', 'Electronics');
INSERT INTO PRODUCTS VALUES ('6', 'Samsung S21', 'Samsung', 'Electronics');
INSERT INTO PRODUCTS VALUES ('7', 'Samsung Tab S8', 'Samsung', 'Electronics');
INSERT INTO PRODUCTS VALUES ('8', 'Huawei P40', 'Huawei', 'Electronics');
INSERT INTO PRODUCTS VALUES ('9', 'Huawei P50', 'Huawei', 'Electronics');
INSERT INTO PRODUCTS VALUES ('10', 'Women Cardigan', 'Uniqlo', 'Apparal');
INSERT INTO PRODUCTS VALUES ('11', 'Men Shirt', 'Uniqlo', 'Apparal');
INSERT INTO PRODUCTS VALUES ('12', 'Men Shoes', 'Adidas', 'Apparal');
INSERT INTO PRODUCTS VALUES ('13', 'Women Shoes', 'Adidas', 'Apparal');
INSERT INTO PRODUCTS VALUES ('14', 'LV Belt bag', 'LV', 'Apparal');
INSERT INTO PRODUCTS VALUES ('15', 'LV Chain bag', 'LV', 'Apparal');
INSERT INTO PRODUCTS VALUES ('16', 'IKEA Desk', 'IKEA', 'Lifestyle');
INSERT INTO PRODUCTS VALUES ('17', 'IKEA Chair', 'IKEA', 'Lifestyle');
INSERT INTO PRODUCTS VALUES ('18', 'MUJI Container', 'MUJI', 'Lifestyle');
INSERT INTO PRODUCTS VALUES ('19', 'MUJI Stocker', 'MUJI', 'Lifestyle');
INSERT INTO PRODUCTS VALUES ('20', 'MUJI Basket', 'MUJI', 'Lifestyle');
